name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check --verbose
    - name: Lint and Format
      run: cargo clippy && cargo fmt --check
    - name: Run tests
      run: cargo test --verbose
